#include <fstream>
#include <vector>
void pardrawscript()
{
  cout<<"start"<<endl;
  //TH1D *h1=new TH1D("h1","factor e",50,0.98,1.02);
  //TH1D *h2=new TH1D("h2","factor mu",30,0.95,1.05);
  //TH1D *h3=new TH1D("h3","factor pi(ee)",30,0.95,1.05);
  //TH1D *h4=new TH1D("h4","factor pi(mumu)",30,0.95,1.05);
  TH1D *h1=new TH1D("h","correction factor for pi",30,0.95,1.05);
  ifstream in1("parpipill");
  ifstream in2("parkpi");
  ifstream in3("parkpipi");
  double factore;
  double factormu;
  double factorpi1;
  double factorpi2;
  double factorpi3;
  //double factorelow;
  //double factoreup;
  double factoreerr;
  double factormuerr;
  double factorpi1err;
  double factorpi2err;
  double factorpi3err;
  double energy=0;
  vector<double> x,y1,y2,y3,xe,y1e,y2e,y3e;//y1elow,y1eup;

  x.clear();
  xe.clear();
  y1.clear();
  y2.clear();
  y3.clear();
  //y1elow.clear();
  //y1eup.clear();
  y1e.clear();
  y2e.clear();
  y3e.clear();
  char tmpstr[1000];
  getline(in1,tmpstr);
  while(!in1.eof()){
    in1>>energy;
    //energy+=1;
    //getline(in,tmpstr);
    //getline(in,tmpstr);
    in1>>factore>>factoreerr;
    in1>>factormu>>factormuerr;
    in1>>factorpi1>>factorpi1err;
    //getline(in,tmpstr);
    getline(in1,tmpstr);
    //h1->Fill(factore);
    //h2->Fill(factormu);
    //h3->Fill(factorpi);
    //if(fabs(factorpierr)>1) continue;
    x.push_back(energy);
    xe.push_back(0.0);
    y1.push_back(factorpi1);
    y1e.push_back(factorpi1err);
    //y1elow.push_back(factorelow);
    //y1eup.push_back(factoreup);
    //y2.push_back(factormu);
    //y2e.push_back(factormuerr);
    //y3.push_back(factorpi);
    //y3e.push_back(factorpierr);
  }
  getline(in2,tmpstr);
  while(!in2.eof()){
    in2>>energy;
    //energy+=1;
    in2>>factorpi2>>factorpi2err;
    getline(in2,tmpstr);
    //h1->Fill(factore);
    //h2->Fill(factormu);
    //h3->Fill(factorpi);
    //if(fabs(factorpierr)>1) continue;
    //x.push_back(energy);
    //xe.push_back(0.0);
    y2.push_back(factorpi2);
    y2e.push_back(factorpi2err);
    //y1elow.push_back(factorelow);
    //y1eup.push_back(factoreup);
    //y2.push_back(factormu);
    //y2e.push_back(factormuerr);
    //y3.push_back(factorpi);
    //y3e.push_back(factorpierr);
  }
  getline(in3,tmpstr);
  while(!in3.eof()){
    in3>>energy;
    //energy+=1;
    in3>>factorpi3>>factorpi3err;
    //getline(in,tmpstr);
    getline(in3,tmpstr);
    //h1->Fill(factore);
    //h2->Fill(factormu);
    //h3->Fill(factorpi);
    //if(fabs(factorpierr)>1) continue;
    //x.push_back(energy);
    //xe.push_back(0.0);
    y3.push_back(factorpi3);
    y3e.push_back(factorpi3err);
    //y1elow.push_back(factorelow);
    //y1eup.push_back(factoreup);
    //y2.push_back(factormu);
    //y2e.push_back(factormuerr);
    //y3.push_back(factorpi);
    //y3e.push_back(factorpierr);
  }
  //h1->Fit("gaus");
  //h2->Fit("gaus");
  //h3->Fit("gaus");

  const double n=x.size()-1;
  //const double n=104;
  double ene[n],enee[n];
  double fpi1[n],fpi1e[n],fpi2[n],fpi2e[n],fpi3[n],fpi3e[n];
  //double fe[n],feelow[n],feeup[n];
  //double fmu[n],fmue[n];
  //double fpi[n],fpie[n];
  for(int i=0;i<n;i++){
    ene[i]=x.at(i);
    enee[i]=0;
    fpi1[i] =y1.at(i);
    fpi1e[i]=y1e.at(i);
    fpi2[i] =y2.at(i);
    fpi2e[i]=y2e.at(i);
    fpi3[i] =y3.at(i);
    fpi3e[i]=y3e.at(i);

    //fe[i]=y1.at(i);
    //feelow[i]=fe[i]-y1elow.at(i);
    //feeup[i]=y1eup.at(i)-fe[i];
    //fmu[i]=y2.at(i);
    //fmue[i]=y2e.at(i);
    //fpi[i]=y3.at(i);
    //fpie[i]=y3e.at(i);
  }
  
  //gStyle->SetOptFit(1111);
  //TF1 *f=new TF1("f","[0]",3800,4600);
  //f->SetParameter(0,1.0);
  cout<<"create graph,n point "<<n<<endl;
  //TGraphAsymmErrors *graph1=new TGraphAsymmErrors(n,ene,fe,enee,enee,feelow,feeup);
  TGraphErrors *graph1=new TGraphErrors(n,ene,fpi1,enee,fpi1e);
  TGraphErrors *graph2=new TGraphErrors(n,ene,fpi2,enee,fpi2e);
  TGraphErrors *graph3=new TGraphErrors(n,ene,fpi3,enee,fpi3e);
  graph1->SetMinimum(0.995);
  graph1->SetMaximum(1.005);
  graph2->SetMinimum(0.995);
  graph2->SetMaximum(1.005);
  graph3->SetMinimum(0.995);
  graph3->SetMaximum(1.005);
  //TGraphErrors *graph2=new TGraphErrors(n,ene,fmu,enee,fmue);
  //graph2->SetMarkerStyle(5);
  //graph2->Fit(f);
  //graph2->SetMinimum(0.95);
  //graph2->SetMaximum(1.05);
  //TGraphErrors *graph3=new TGraphErrors(n,ene,fpi,enee,fpie);
  //graph3->SetMarkerStyle(5);
  //graph3->SetMinimum(0.95);
  //graph3->SetMaximum(1.05);
  //graph3->Fit(f);
  TCanvas *c1=new TCanvas();
  graph1->Draw("AP");
  graph2->Draw("same");
  graph3->Draw("same");
  graph1->SetMarkerStyle(2);
  graph1->SetMarkerColor(2);
  graph1->SetLineColor(2);
  graph2->SetMarkerStyle(4);
  graph2->SetMarkerColor(3);
  graph2->SetLineColor(3);
  graph3->SetMarkerStyle(5);
  graph3->SetMarkerColor(4);
  graph3->SetLineColor(4);
  TLegend *legend=new TLegend(0.70,0.75,0.90,0.90);
  legend->AddEntry(graph1,"pi factor from pipill");
  legend->AddEntry(graph2,"pi factor from kpi");
  legend->AddEntry(graph3,"pi factor from kpipi");
  legend->Draw();
  //c1->Divide(2,2);
  //c1->cd(1);
  //c1->Print("factorse.eps");
  //c1->cd(2);
  //graph2->Draw("AP");
  //c1->Print("factorsmu.eps");
  //c1->cd(3);
  //graph3->Draw("AP");
  //c1->Print("factorspi.eps");
  //exit();
}
