/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROORELATIVISTICBW
#define ROORELATIVISTICBW

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

//#include "Rtypes.h"

class RooRelativisticBW : public RooAbsPdf {
public:
  RooRelativisticBW() {} ; 
  RooRelativisticBW(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mean,
	      RooAbsReal& _width);
  RooRelativisticBW(const RooRelativisticBW& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooRelativisticBW(*this,newname); }
  inline virtual ~RooRelativisticBW() { }

protected:

  RooRealProxy x ;
  RooRealProxy mean ;
  RooRealProxy width ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooRelativisticBW,1) // RooRelativisticBw
};
 
#endif
